runtime: nodejs22

instance_class: F1

service: frontend

handlers:
- url: /(.*\..+)$
  static_files: .build/\1
  upload: .build/(.*\..+)$

- url: /.*
  static_files: .build/index.html
  secure: always
  redirect_http_response_code: 301
  script: auto
